name: blott_app
description: 'A new Flutter project.'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # state management
  flutter_bloc: ^8.1.6

  # comparing dart objects
  equatable: ^2.0.5

  # service locator
  get_it: ^7.7.0

  # date format
  intl: ^0.19.0

  # make request to api
  retrofit: ^4.4.1

  # chached image
  cached_network_image: ^3.4.1

  # font
  google_fonts: ^6.2.1

  # url launcher
  url_launcher: ^6.3.0

  # local storage
  shared_preferences: ^2.3.2

  # permission
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
